development: &my_settings
  enable_star: true
  min_infix_len: 1
  charset_type: utf-8
  morphology: stem_ru
  charset_table: "0..9, a..z, _, @, A..Z->a..z, U+410..U+42F->U+430..U+44F, U+430..U+458"
test:
  <<: *my_settings
production:
  <<: *my_settings     